server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hdilhara/micro-services-codelab
          search-paths:
           - 'ConfigStore'
          #username: root
          #passphrase: 123
