server:
  port: 8091

###  my configurations are store in locally
#spring:
#  profiles:
#    active: native

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hdilhara/spring-cloud-config-server
          search-paths:
           - '*service'
          #username: root
          #passphrase: 123
